### ISSUE TITLE
What config does commitsar use?

### ISSUE THREAD

**Issue by tysonnero** [outillage/commitsar#124]
Will commitsar use the `.commitlintrc.js` in the root of the repo, or does it use its own config?

**Comment by fallion** [comment]
Hi, 
It doesn't have a config yet. :(

**Comment by fallion** [comment]
Just out of curiosity what kind of config would you like?

**Comment by tysonnero** [comment]
We actually have a `.commitlintrc.js` file in the root of our repo which commitlint uses locally for hooks and such. Would there be anyway for `commitsar` to pick up the existing of a local config file (https://github.com/conventional-changelog/commitlint#config), otherwise fallback to `@commitlint/config-conventional`?

**Comment by fallion** [comment]
I'll look into it.

**Comment by tysonnero** [comment]
Thank you! I didn't realize you all wrote a custom rules engine until I just looked through the source code. I figured it was `commitlint` under the hood. This is very impressive.

**Comment by fallion** [comment]
Had a look at this issue and there is a slight problem. Commitlint uses JS files to set rules, I'd like to avoid trying to parse that as JSON or YML would be not problematic, however the fact that functions can be used as rules kind of complicates parsing.

**Comment by fallion** [comment]
Closing this as stale. Unless you have an idea on how to use it.
