### ISSUE TITLE
improvement log management

### ISSUE THREAD

**Issue by msAlcantara** [outillage/commitsar#126]
I'm suggest to add some package to management the log messages like [logrus](https://github.com/sirupsen/logrus), and stop to make 
```go
if debug {
    fmt.Printf("[DEBUG].......")
}
```
and add something like this on startup
 ```go
if verboseFlag {
    logrus.SetLevel(logrus.DebugLevel)
}
```

and use like this
```go
logrus.Debugf("..........")
```

**Comment by fallion** [comment]
Thanks for the issue :) There's a similar one that I was planning to implement. https://github.com/commitsar-app/commitsar/issues/88
