### ISSUE TITLE
Use refs from CLI args rather than check against master

### ISSUE THREAD

**Issue by Multiply** [outillage/commitsar#165]
Would it be possible to use refs instead of checking against master specifically?

In our test setup, the pipeline doesn't have to test a given branch, or a known sha, but will rather merge, or rebase and generare a new sha.

I'd love to be able to have a CLI flag which will be used to find relevant commits, rather than checking against master.

Example input to said CLI flag: `00eb86529a18a07e8e04c69daf34b4f539555fd0...3a5ab85fb13ae8d37925e37ea56eee8834eee854`

**Comment by fallion** [comment]
Hi,
Definitely doable. Putting on my todo list for this week.

**Comment by fallion** [comment]
Hi @Multiply,

This has now been merged into upstream. Can you give it a try? https://github.com/outillage/commitsar#flags

**Comment by Multiply** [comment]
@fallion I'll test it right away.

**Comment by Multiply** [comment]
@fallion it seems like the order of the SHA's are reversed.

The first SHA should be the base, and the second SHA should be the newest commit that was merged in, for example.

**Comment by fallion** [comment]
Hmm. It uses git log under the hood which will start from the newest and iterate to the oldest commit.

So FROM is the newer commit TO is the older commit.

**Comment by fallion** [comment]
I see now. Will flip it so it maintains the same usage as git log.

**Comment by fallion** [comment]
Flipped them. Let me know any other issues @Multiply

**Comment by Multiply** [comment]
I'll test it again today.

**Comment by Multiply** [comment]
With your latest released version, I am getting:

```
$ commitsar 5cf43d427b3eca3b51d74a6532920051f6085535...596a90ce88553ab60f165ec6c2239777dd45d557
unknown command "5cf43d427b3eca3b51d74a6532920051f6085535...596a90ce88553ab60f165ec6c2239777dd45d557" for "commitsar"
```

**Comment by fallion** [comment]
Going to investigate and add further regression tests.

**Comment by fallion** [comment]
Yes. This is a regression. Adding #176 disabled the CLI args. Will make a change in #168 to be a flag rather than a command.

**Comment by fallion** [comment]
Regression fixed in latest master. Let me know if any more adjustments are needed for your use case.

**Comment by fallion** [comment]
Hi @Multiply, was the issue fixed? Just so I know whether to close this issue.

**Comment by Multiply** [comment]
@fallion Seems to work as expected. Thanks!
