### ISSUE TITLE
add "version" flag or command

### ISSUE THREAD

**Issue by tommyalatalo** [outillage/commitsar#168]
Its unnecessarily difficult to check which version of the commitsar binary you have at the moment, adding a "--version" flag or a "commitsar version" command would solve this.

**Comment by fallion** [comment]
Version command has been added: `commitsar version` will now print the version info for given binary.

**Comment by fallion** [comment]
Let me know if any adjustments are needed @tommyalatalo

**Comment by tommyalatalo** [comment]
Your pipeline is not working properly, I just downloaded v0.10.0 for linux x86_64, the version command output is this: `Commitsar version: development	 Built on:`

It should say "v0.10.0" since its a release, no?

**Comment by fallion** [comment]
Seems the goreleaser part needs some adjustments. Sorry about that. Going to reopen and fix.

**Comment by fallion** [comment]
@tommyalatalo I will move this to a flag. It causes a clash when CLI args are passed in. ETA today with Goreleaser fix as well.

**Comment by fallion** [comment]
Resolved in https://github.com/outillage/commitsar/releases/tag/v0.10.1
