### ISSUE TITLE
Breaking change syntax with no commit body fails validation

### ISSUE THREAD

**Issue by michaelfig** [outillage/commitsar#207]
According to https://www.conventionalcommits.org/en/v1.0.0/:

3. BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any type.

When I committed: `feat!: use git clone for agoric init', it came back with:

```
FAIL   cbc82f35c5e1f1d81389e01d0ccae31660f97f9d   use git clone for agoric init   breaking change must contain commit body
```

Example given in the spec that doesn't contain a commit body: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-to-draw-attention-to-breaking-change

**Comment by fallion** [comment]
Hi @michaelfig ,
Thanks for the report. I am making a point to fix it tomorrow. Sorry about that.

**Comment by fallion** [comment]
Releasing now.

**Comment by michaelfig** [comment]
Thanks!

**Comment by jeanplevesque** [comment]
I think I have the same problem:
My commit:
`ci!: Improve package metadata for v1.0.0.`

The output:
```
FAIL   fc0b7d901e69663a444e31f44b87da1d5c61a098   Improve package metadata for v1.0.0.   breaking change must contain commit body
```
