### ISSUE TITLE
Allow special characters in scopes

### ISSUE THREAD

**Issue by CodingJonas** [outillage/commitsar#217]
To my knowledge the specification for conventional commits does not limit scopes to letters, but allow any special character. 

I noticed you use this regex pattern to check the validity of scopes:

```
^\w+( \w+)*$
```

What's the reason behind only allowing words and whitespaces? I think allowing e.g. dashes could be useful.

**Comment by fallion** [comment]
A lot of this was based on usage. We'll add dashes and non bracket characters to allowed. I'll try to ship a fix today/tomorrow.

Thanks for the issue :)

**Comment by CodingJonas** [comment]
Awesome! Thank you for the quick response :)

**Comment by fallion** [comment]
Slight delay, moving it in with some other fixes that were planned. Sorry about that.
